### ISSUE TITLE
tiny-invariant throws on an empty string

### ISSUE THREAD

**Issue by jasikpark** [alexreardon/tiny-invariant#174]
I use https://github.com/fram-x/assert-ts#check-condition for my simple code assertions, which allows me to narrow `string | null | undefined` to `string` w/o throwing an error on an empty string. tiny-invariant differs in that - is that intentional?

I find it confusing, since `""` is still a string, but it does more clearly follow the `if(!condition)` pattern more directly, though you can achieve the same w/ `assert-ts` with `assert(!!possiblyNullishOrEmptyString)` to cause it to throw on an empty string

 [codesandbox.io/s/assert-v-s-tiny-invariant-z2w4gq](https://codesandbox.io/s/assert-v-s-tiny-invariant-z2w4gq)

**Comment by stof** [comment]
tiny-invariant is explicitly documenting as checking whether the value passed as condition is falsy.

assert-ts has 2 signatures:
- when passing a boolean, it checks for false
- when passing anything else, it checks if the value is nullish

A check for nullish or a check for falsy will not be equivalent.

**Comment by alexreardon** [comment]
From the description of this library:

> An invariant function takes a value, and if the value is [falsy](https://github.com/getify/You-Dont-Know-JS/blob/bdbe570600d4e1107d0b131787903ca1c9ec8140/up%20%26%20going/ch2.md#truthy--falsy) then the invariant function will throw. If the value is [truthy](https://github.com/getify/You-Dont-Know-JS/blob/bdbe570600d4e1107d0b131787903ca1c9ec8140/up%20%26%20going/ch2.md#truthy--falsy), then the function will not throw.

`""` is falsy, and so will result in a `throw`.

If you don't want to throw on `""` you could make your `condition` more explicit

```ts
invariant(typeof value === 'string' && value !== '');
```
