### ISSUE TITLE
Provide repository to package.json for WebJars compatibility

### ISSUE THREAD

**Issue by trathschlag** [alexreardon/tiny-invariant#19]
I am trying to use tiny-invariant with webjars.org and get the following error:

`The metadata was missing a required field: /repository/url`
This could be easily fixed by adding the information to the `package.json`:

```json
"repository": {
  "type" : "git",
  "url" : "..."
}
```
Thanks in advance!

**Comment by alexreardon** [comment]
PR welcome!
