### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ajkl2533** [alexreardon/tiny-invariant#27]
Hi, would you mind adding the MIT license file to the repo & the npm package? MIT license actually requires full license text to be distributed along the source code. You can find license text here https://opensource.org/licenses/MIT. 

Many thanks.

**Comment by alexreardon** [comment]
Yep, this project is MIT. Thanks for calling this out

**Comment by alexreardon** [comment]
Will be fixed in #31
