### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by alexreardon** [alexreardon/tiny-invariant#45]
Right now we are sort of blocked given that there needs to be no way to do an `invariant` style guard

**Comment by alexreardon** [comment]
I will be moving to TS 3.7 guards

**Comment by alexreardon** [comment]
Done https://github.com/alexreardon/tiny-invariant/releases/tag/v1.1.0

Enjoy!

**Comment by karlhorky** [comment]
Awesome, thanks for your work on this Alex!
