### ISSUE TITLE
Flow issue

### ISSUE THREAD

**Issue by viktor-equinix** [alexreardon/tiny-invariant#61]
In 1.1.0 you renamed files(comparing with 1.0.4) and file https://github.com/alexreardon/tiny-invariant/blob/master/src/tiny-invariant.ts contains `// @flow` which creates an error in flow.

Please remove this line as this is not flow type file

**Comment by osmestad** [comment]
This breaks our build too now, any hope of a release with a fix? 
Can make a PR that removes the `// @flow` line if you like :-D
Have not traced down where if our dependency graph this library is used yet.

**Comment by alexreardon** [comment]
PR welcome
