### ISSUE TITLE
Accept generator function for error message

### ISSUE THREAD

**Issue by davidje13** [alexreardon/tiny-invariant#62]
For dev-time error messages (and for those not using build-time rewriters), it would be nice if time-consuming calculations for error messages were only performed in the event of an error. This would be easy to achieve with minimal bloat using a lambda:

```js
invariant(something, () => `my message with ${complex()} calculations`)
```

The build-time rewriters will be able to strip this with no changes necessary.

Internally:

```js
throw new Error(`${prefix}: ${typeof message == 'function' ? message() : message || ''}`);
```

**Comment by alexreardon** [comment]
🤔

**Comment by alexreardon** [comment]
How does this look @davidje13? https://github.com/alexreardon/tiny-invariant/pull/76/files

**Comment by alexreardon** [comment]
Closed by mistake

**Comment by alexreardon** [comment]
Now released https://github.com/alexreardon/tiny-invariant/releases/tag/v1.2.0
